insert into ELIGIBILITY_DTLS (PLAN_ID, PLAN_NAME,PLAN_STATUS,BENEFIT_AMOUNT,START_DATE,END_DATE) values (101,'SNAP','approved',100.0,'2022-05-13','2020-05-30');
insert into ELIGIBILITY_DTLS (PLAN_ID, PLAN_NAME,PLAN_STATUS,BENEFIT_AMOUNT,START_DATE,END_DATE) values (102,'SNAP','approved',100.0,'2022-05-13','2020-05-30');
insert into ELIGIBILITY_DTLS (PLAN_ID, PLAN_NAME,PLAN_STATUS,DENIAL_REASON) values (103,'SNAP','denied','High Salary Income');
insert into ELIGIBILITY_DTLS (PLAN_ID, PLAN_NAME,PLAN_STATUS,DENIAL_REASON) values (104,'SNAP','denied','High Rent Income');

insert into ELIGIBILITY_DTLS (PLAN_ID, PLAN_NAME,PLAN_STATUS,BENEFIT_AMOUNT,START_DATE,END_DATE) values (105,'CCAP','approved',100.0,'2022-05-13','2020-05-30');
insert into ELIGIBILITY_DTLS (PLAN_ID, PLAN_NAME,PLAN_STATUS,BENEFIT_AMOUNT,START_DATE,END_DATE) values (106,'CCAP','approved',100.0,'2022-05-13','2020-05-30');
insert into ELIGIBILITY_DTLS (PLAN_ID, PLAN_NAME,PLAN_STATUS,DENIAL_REASON) values (107,'CCAP','denied','Kids Not Available');
insert into ELIGIBILITY_DTLS (PLAN_ID, PLAN_NAME,PLAN_STATUS,DENIAL_REASON) values (108,'CCAP','denied','Kids Age Above 16 years');


insert into ELIGIBILITY_DTLS (PLAN_ID, PLAN_NAME,PLAN_STATUS,BENEFIT_AMOUNT,START_DATE,END_DATE) values (109,'Medicaid','approved',100.0,'2022-05-13','2020-05-30');
insert into ELIGIBILITY_DTLS (PLAN_ID, PLAN_NAME,PLAN_STATUS,BENEFIT_AMOUNT,START_DATE,END_DATE) values (110,'Medicaid','approved',100.0,'2022-05-13','2020-05-30');
insert into ELIGIBILITY_DTLS (PLAN_ID, PLAN_NAME,PLAN_STATUS,DENIAL_REASON) values (111,'Medicaid','denied','High Income');
insert into ELIGIBILITY_DTLS (PLAN_ID, PLAN_NAME,PLAN_STATUS,DENIAL_REASON) values (112,'Medicaid','denied','High Property Income');


insert into ELIGIBILITY_DTLS (PLAN_ID, PLAN_NAME,PLAN_STATUS,BENEFIT_AMOUNT,START_DATE,END_DATE) values (113,'Medicare','approved',100.0,'2022-05-13','2020-05-30');
insert into ELIGIBILITY_DTLS (PLAN_ID, PLAN_NAME,PLAN_STATUS,BENEFIT_AMOUNT,START_DATE,END_DATE) values (114,'Medicare','approved',100.0,'2022-05-13','2020-05-30');
insert into ELIGIBILITY_DTLS (PLAN_ID, PLAN_NAME,PLAN_STATUS,DENIAL_REASON) values (115,'Medicare','denied','High Income');
insert into ELIGIBILITY_DTLS (PLAN_ID, PLAN_NAME,PLAN_STATUS,DENIAL_REASON) values (116,'Medicare','denied','Age Not Matching');


insert into ELIGIBILITY_DTLS (PLAN_ID, PLAN_NAME,PLAN_STATUS,BENEFIT_AMOUNT,START_DATE,END_DATE) values (117,'QHP','approved',100.0,'2022-05-13','2020-05-30');
insert into ELIGIBILITY_DTLS (PLAN_ID, PLAN_NAME,PLAN_STATUS,BENEFIT_AMOUNT,START_DATE,END_DATE) values (118,'QHP','approved',100.0,'2022-05-13','2020-05-30');
insert into ELIGIBILITY_DTLS (PLAN_ID, PLAN_NAME,PLAN_STATUS,DENIAL_REASON) values (119,'QHP','denied','expired');
insert into ELIGIBILITY_DTLS (PLAN_ID, PLAN_NAME,PLAN_STATUS,DENIAL_REASON) values (120,'QHP','denied','expired');